"""
print("Hello world.")
print("Nice")
print("How are you")
print(5*5)

# 4.1 Print Excersises / P.g 13

print("Nicholas")
print("Mrs White")
print("King's High")
print("15")
print("2047")
print("115")
print(658/7)
print("A long time ago")
print("Apex legends")
print("Digi Tec")
"""

#Data Types/ 4.4 Excercises / p.g 17
print("\n")
print("Never gonna give you up\n Never gonna let you down\n Never gonna run around\n and desert you Never gonna make you cry")
print("\n")
print("Star Wars Episode 1 The Phantom menace\n Ex squeezee me.")
print("\n")
print("A string is a line of characters incased in quotation marks.")
print("\n")
print("An interger is a whole number.")
print("\n")
print("A float is the oposite of an interger because it includes fractions of numbers.")
print("\n")
print(543/3)
print("\n")
print(1000%9)
print("\n")
print(434)
print(434/10)
print("\n")
print(3%2)
print("\n")
print(5%5)
print("\n")
print(555/2)
print("\n")
print(123/2)
print("\n")
print(123/2)
print("\n")
print(123%2)
print("\n")
print(764%2)
print("\n")
print(165/2)


